import type { ManualKnowledgeEntry, ManualUserRole } from '../types/userManualChatbot.types';

const moduleByUseCase: Record<string, string> = {
  'CU-01': 'Gestion de usuarios, acceso y suscripcion',
  'CU-02': 'Gestion de usuarios, acceso y suscripcion',
  'CU-03': 'Gestion de usuarios, acceso y suscripcion',
  'CU-04': 'Gestion de usuarios, acceso y suscripcion',
  'CU-05': 'Gestion de usuarios, acceso y suscripcion',
  'CU-06': 'Gestion de usuarios, acceso y suscripcion',
  'CU-07': 'Marketplace de platos',
  'CU-08': 'Marketplace de platos',
  'CU-09': 'Marketplace de platos',
  'CU-10': 'Marketplace de platos',
  'CU-11': 'Marketplace de platos',
  'CU-12': 'Gestion del cocinero',
  'CU-13': 'Gestion del cocinero',
  'CU-14': 'Gestion del cocinero',
  'CU-15': 'Gestion del cocinero',
  'CU-16': 'Gestion del cocinero',
  'CU-17': 'Gestion del cocinero',
  'CU-18': 'Gestion del cocinero',
  'CU-19': 'Gestion del cocinero',
  'CU-20': 'Asistencia inteligente para cocineros',
  'CU-21': 'Asistencia inteligente para cocineros',
  'CU-22': 'Asistencia inteligente para cocineros',
  'CU-23': 'Asistencia inteligente para cocineros',
  'CU-24': 'Pedidos, checkout y pagos',
  'CU-25': 'Pedidos, checkout y pagos',
  'CU-26': 'Pedidos, checkout y pagos',
  'CU-27': 'Pedidos, checkout y pagos',
  'CU-28': 'Pedidos, checkout y pagos',
  'CU-29': 'Pedidos, checkout y pagos',
  'CU-30': 'Pedidos, checkout y pagos',
  'CU-31': 'Delivery y logistica',
  'CU-32': 'Delivery y logistica',
  'CU-33': 'Delivery y logistica',
  'CU-34': 'Delivery y logistica',
  'CU-35': 'Confianza, administracion, seguridad y notificaciones',
  'CU-36': 'Confianza, administracion, seguridad y notificaciones',
  'CU-37': 'Confianza, administracion, seguridad y notificaciones',
  'CU-38': 'Confianza, administracion, seguridad y notificaciones',
};

const useCaseSeeds = [
  ['CU-01', 'Gestionar registro de usuario', ['visitante'], ['/register'], ['Registro'], 'Crea una cuenta para usar HomeChef.', ['Abre Registrarse.', 'Completa tus datos.', 'Confirma el registro e inicia sesion.'], ['registro', 'registrarme', 'crear cuenta']],
  ['CU-02', 'Gestionar sesion', ['visitante', 'cliente', 'cocinero', 'admin', 'repartidor'], ['/login'], ['Inicio de sesion'], 'Permite iniciar y cerrar sesion segun tu rol.', ['Abre Iniciar sesion.', 'Ingresa tus credenciales.', 'Usa Cerrar sesion al terminar.'], ['login', 'iniciar sesion', 'cerrar sesion']],
  ['CU-03', 'Recuperar contrasena', ['visitante', 'usuario'], ['/recover-password', '/reset-password'], ['Recuperar contrasena'], 'Permite restablecer la contrasena.', ['Abre Recuperar contrasena.', 'Escribe tu correo.', 'Sigue el enlace de recuperacion.'], ['recuperar', 'contrasena', 'olvide']],
  ['CU-04', 'Gestionar perfil', ['cliente', 'cocinero'], ['/client/profile', '/chef/profile'], ['Perfil'], 'Permite revisar y actualizar tus datos.', ['Entra a Perfil.', 'Edita los campos permitidos.', 'Guarda cambios.'], ['perfil', 'datos', 'mi cuenta']],
  ['CU-05', 'Gestionar suscripcion IA del cocinero', ['cocinero'], ['/chef/ai-subscription', '/chef/subscription'], ['Suscripcion IA'], 'Permite contratar o revisar el plan de funciones IA.', ['Entra a Suscripcion IA.', 'Revisa planes.', 'Confirma el metodo de pago disponible.'], ['suscripcion', 'plan ia', 'contratar ia']],
  ['CU-06', 'Gestionar acceso a funciones IA', ['cocinero'], ['/chef/ai/assistant', '/chef/ai-subscription'], ['Asistente IA'], 'Controla el acceso a funciones IA segun suscripcion.', ['Abre Asistente IA.', 'Si esta bloqueado entra a Suscripcion IA.', 'Regulariza tu plan.'], ['acceso ia', 'bloqueado ia', 'permiso ia']],
  ['CU-07', 'Visualizar dashboard publico de platos', ['visitante', 'cliente'], ['/'], ['Dashboard publico'], 'Muestra platos disponibles en el inicio publico.', ['Abre la pagina principal.', 'Explora cards de platos.', 'Entra al detalle si te interesa.'], ['inicio', 'platos publicos', 'dashboard']],
  ['CU-08', 'Explorar dashboard de platos', ['cliente'], ['/client/explore'], ['Explorar platos'], 'Permite buscar y explorar platos disponibles.', ['Entra a Explorar platos.', 'Revisa cards.', 'Abre un plato.'], ['explorar', 'buscar platos', 'marketplace']],
  ['CU-09', 'Consultar detalle de plato', ['visitante', 'cliente'], ['/client/dishes/:id'], ['Detalle de plato'], 'Muestra descripcion, precio y cocinero del plato.', ['Abre un plato.', 'Revisa precio y descripcion.', 'Agrega al carrito si quieres comprar.'], ['detalle', 'ver plato', 'precio plato']],
  ['CU-10', 'Gestionar favoritos y preferencias', ['cliente'], ['/client/favorites'], ['Favoritos'], 'Permite guardar y revisar platos favoritos.', ['Marca un plato como favorito.', 'Entra a Favoritos.', 'Quita favoritos si ya no los quieres.'], ['favoritos', 'guardar plato', 'preferencias']],
  ['CU-11', 'Consultar reputacion desde marketplace', ['visitante', 'cliente'], ['/client/chefs/:id', '/client/dishes/:id'], ['Perfil publico del cocinero'], 'Permite revisar reputacion visible del cocinero.', ['Abre un plato o perfil del cocinero.', 'Revisa informacion visible.', 'Decide antes de comprar.'], ['reputacion', 'calificacion', 'cocinero']],
  ['CU-12', 'Gestionar perfil de cocinero', ['cocinero'], ['/chef/profile'], ['Perfil cocinero'], 'Permite configurar datos visibles y operativos de cocinero.', ['Entra a Perfil cocinero.', 'Completa datos requeridos.', 'Guarda cambios.'], ['perfil cocinero', 'validacion', 'cocina']],
  ['CU-13', 'Gestionar disponibilidad del cocinero', ['cocinero'], ['/chef/availability'], ['Disponibilidad'], 'Permite definir horarios o estado de atencion.', ['Entra a Disponibilidad.', 'Configura horarios.', 'Guarda cambios.'], ['disponibilidad', 'horario', 'abrir cocina']],
  ['CU-14', 'Consultar dashboard del cocinero', ['cocinero'], ['/chef/dashboard'], ['Resumen general'], 'Muestra resumen operativo del cocinero.', ['Entra a Resumen general.', 'Revisa indicadores.', 'Usa el menu lateral.'], ['dashboard', 'resumen', 'panel cocinero']],
  ['CU-15', 'Gestionar publicacion de platos', ['cocinero'], ['/chef/dishes', '/chef/dishes/create'], ['Mis platos', 'Crear plato'], 'Permite crear, editar y gestionar platos publicados.', ['Entra a Mis platos.', 'Crea o edita un plato.', 'Completa nombre, descripcion y precio.', 'Guarda la publicacion.'], ['publicar plato', 'crear plato', 'mis platos']],
  ['CU-16', 'Gestionar menu del dia', ['cocinero'], ['/chef/menu'], ['Menu del dia'], 'Permite organizar que platos estaran disponibles hoy.', ['Entra a Menu del dia.', 'Selecciona platos del catalogo.', 'Define porciones o disponibilidad.', 'Guarda cambios.'], ['menu del dia', 'platos de hoy', 'activar plato']],
  ['CU-17', 'Gestionar inventario e insumos', ['cocinero'], ['/chef/inventory'], ['Inventario'], 'Permite registrar y controlar insumos disponibles.', ['Entra a Inventario.', 'Agrega o actualiza insumos.', 'Revisa cantidades y vencimientos.'], ['inventario', 'insumos', 'stock']],
  ['CU-18', 'Gestionar consumo de insumos por venta', ['cocinero'], ['/chef/inventory', '/chef/orders'], ['Inventario', 'Pedidos recibidos'], 'Permite controlar insumos asociados a ventas.', ['Revisa pedidos vendidos.', 'Actualiza consumo en inventario.', 'Verifica stock restante.'], ['consumo insumos', 'descontar stock', 'venta']],
  ['CU-19', 'Consultar ingresos y comisiones', ['cocinero'], ['/chef/finances'], ['Mis ingresos'], 'Muestra ingresos y datos financieros visibles.', ['Entra a Mis ingresos.', 'Revisa totales y movimientos.', 'Usa filtros si estan disponibles.'], ['ingresos', 'comisiones', 'finanzas']],
  ['CU-20', 'Utilizar asistente inteligente de cocina', ['cocinero'], ['/chef/ai/assistant', '/chef/ai/asistente/use'], ['Asistente inteligente de cocina'], 'Sugiere ideas de platos a partir de ingredientes.', ['Entra a Asistente IA.', 'Abre Asistente de cocina.', 'Escribe ingredientes y contexto.', 'Revisa sugerencias.'], ['asistente cocina', 'recetas ia', 'ideas de platos']],
  ['CU-21', 'Analizar ingredientes mediante vision artificial', ['cocinero'], ['/chef/ai/vision/use'], ['Vision artificial'], 'Analiza imagenes de ingredientes si usas esa funcion IA.', ['Entra a Asistente IA.', 'Abre Vision artificial.', 'Carga una imagen si la pantalla lo permite.', 'Revisa ingredientes detectados.'], ['vision', 'foto ingredientes', 'imagen']],
  ['CU-22', 'Consultar recomendaciones de produccion y precios', ['cocinero'], ['/chef/ai/pricing/use', '/chef/ai/pricing'], ['Demanda y precios'], 'Calcula demanda estimada, cantidad recomendada y precio.', ['Entra a Asistente IA.', 'Abre Demanda y precios.', 'Completa plato, ingredientes y porciones.', 'Revisa precio sugerido y explicacion.'], ['demanda', 'precios', 'cuanto cobrar']],
  ['CU-23', 'Aplicar asistencia IA en publicaciones', ['cocinero'], ['/chef/ai/publication/use', '/chef/ai/publication'], ['Publicacion de platos con IA'], 'Mejora titulo, descripcion, etiquetas y categoria de un plato.', ['Entra a Asistente IA.', 'Abre Publicacion de platos.', 'Completa datos del plato.', 'Copia o adapta la sugerencia.'], ['publicacion ia', 'descripcion plato', 'etiquetas']],
  ['CU-24', 'Gestionar carrito', ['cliente'], ['/client/cart'], ['Carrito'], 'Permite revisar platos agregados antes de comprar.', ['Agrega platos desde el detalle.', 'Entra a Carrito.', 'Revisa cantidades.', 'Continua al checkout.'], ['carrito', 'comprar', 'canasta']],
  ['CU-25', 'Gestionar checkout del pedido', ['cliente'], ['/client/checkout'], ['Checkout'], 'Permite confirmar entrega y resumen del pedido.', ['Entra a Checkout.', 'Elige delivery o retiro si esta disponible.', 'Revisa resumen.', 'Continua al pago.'], ['checkout', 'confirmar pedido', 'direccion']],
  ['CU-26', 'Gestionar pago del pedido', ['cliente'], ['/client/payments/stripe/return', '/client/payments/bitcoin-coingate/return', '/client/payments/qr-simulado'], ['Pago del pedido'], 'Permite completar o revisar resultado del pago.', ['Elige metodo de pago.', 'Completa el pago.', 'Vuelve a HomeChef.', 'Revisa el pedido.'], ['pago', 'qr', 'stripe', 'coingate']],
  ['CU-27', 'Gestionar pedido del cliente', ['cliente'], ['/client/orders', '/client/orders/:id'], ['Mis pedidos'], 'Permite revisar pedidos realizados por el cliente.', ['Entra a Mis pedidos.', 'Abre un pedido.', 'Consulta estado y detalle.'], ['mis pedidos', 'estado pedido', 'pedido cliente']],
  ['CU-28', 'Gestionar pedidos recibidos', ['cocinero'], ['/chef/orders', '/chef/orders/:id'], ['Pedidos recibidos'], 'Permite al cocinero revisar y atender pedidos recibidos.', ['Entra a Pedidos recibidos.', 'Abre el pedido.', 'Revisa platos y estado.', 'Actualiza segun acciones disponibles.'], ['pedidos recibidos', 'aceptar pedido', 'orden']],
  ['CU-29', 'Realizar seguimiento del pedido', ['cliente', 'cocinero'], ['/client/orders/:id/tracking', '/chef/orders/:id/tracking'], ['Seguimiento del pedido'], 'Permite ver avance del pedido y entrega.', ['Abre el pedido.', 'Entra a seguimiento.', 'Revisa estado actual.'], ['seguimiento', 'tracking', 'rastrear pedido']],
  ['CU-30', 'Consultar historial de pedidos', ['cliente', 'cocinero'], ['/client/orders', '/chef/orders'], ['Historial de pedidos'], 'Permite revisar pedidos pasados desde la lista.', ['Entra a la pantalla de pedidos.', 'Busca pedidos anteriores.', 'Abre el detalle si necesitas.'], ['historial', 'pedidos anteriores']],
  ['CU-31', 'Gestionar delivery del pedido', ['repartidor', 'cliente', 'cocinero', 'admin'], ['/delivery/assigned', '/delivery/active', '/admin/delivery-orders', '/client/orders/:id/tracking'], ['Entregas asignadas', 'Entregas activas'], 'Permite coordinar pedidos con entrega a domicilio.', ['Cliente elige delivery en checkout.', 'El pedido se gestiona segun rol.', 'Repartidor revisa entregas.', 'Cliente sigue el estado.'], ['delivery', 'entrega', 'domicilio']],
  ['CU-32', 'Gestionar retiro en punto del cocinero', ['cliente', 'cocinero'], ['/client/checkout', '/chef/orders'], ['Retiro en punto'], 'Permite coordinar retiro del pedido sin delivery.', ['En checkout elige retiro si esta disponible.', 'Confirma pedido.', 'Revisa indicaciones del cocinero.'], ['retiro', 'recoger pedido', 'pickup']],
  ['CU-33', 'Optimizar rutas de entrega', ['repartidor', 'admin'], ['/delivery/routes', '/admin/delivery-orders'], ['Ruta actual'], 'Permite revisar rutas de entrega.', ['Entra a Ruta actual.', 'Revisa entregas activas.', 'Sigue el orden indicado.', 'Reporta incidencias si algo cambia.'], ['ruta', 'rutas', 'mapa delivery']],
  ['CU-34', 'Gestionar incidencias de entrega', ['repartidor', 'admin', 'cliente', 'cocinero'], ['/delivery/incidents', '/admin/delivery-orders'], ['Incidencias'], 'Permite registrar o revisar problemas de entrega.', ['Entra a Incidencias.', 'Registra el problema.', 'Describe la situacion.', 'Da seguimiento.'], ['incidencia', 'problema entrega', 'demora']],
  ['CU-35', 'Gestionar resenas y calificaciones', ['cliente', 'cocinero', 'admin'], ['/client/orders', '/client/dishes/:id', '/client/chefs/:id'], ['Resenas'], 'Permite consultar o gestionar reputacion y calificaciones.', ['Revisa detalle de plato o perfil.', 'Consulta calificaciones visibles.', 'Califica despues de comprar si esta disponible.'], ['resena', 'calificacion', 'opinion']],
  ['CU-36', 'Controlar calidad de publicaciones', ['admin'], ['/admin/publications', '/admin/fraud'], ['Publicaciones', 'Fraude y riesgo'], 'Permite revisar publicaciones sospechosas, falsas o de baja calidad.', ['Entra a Publicaciones o Fraude y riesgo.', 'Revisa publicaciones marcadas.', 'Analiza datos visibles.', 'Aplica la accion administrativa disponible.'], ['publicaciones falsas', 'calidad', 'moderacion']],
  ['CU-37', 'Gestionar usuarios, cocineros y publicaciones', ['admin'], ['/admin/users', '/admin/chefs', '/admin/publications'], ['Usuarios', 'Cocineros', 'Publicaciones'], 'Permite revisar usuarios, validar cocineros y administrar publicaciones.', ['Entra al panel admin.', 'Abre Usuarios, Cocineros o Publicaciones.', 'Revisa registros.', 'Ejecuta acciones disponibles.'], ['admin', 'usuarios', 'cocineros']],
  ['CU-38', 'Monitorear seguridad, fraude y notificaciones', ['admin', 'cliente', 'cocinero'], ['/admin/fraud', '/client/notifications', '/chef/notifications'], ['Fraude y riesgo', 'Notificaciones'], 'Permite monitorear alertas, fraude y notificaciones segun rol.', ['Admin entra a Fraude y riesgo.', 'Cliente o cocinero entra a Notificaciones.', 'Revisa mensajes o alertas.'], ['seguridad', 'fraude', 'notificaciones']],
] as const;

const useCaseEntries: ManualKnowledgeEntry[] = useCaseSeeds.map(([id, title, roles, routes, screens, description, steps, keywords]) => ({
  id,
  title,
  entryType: 'use_case',
  roles: roles as ManualUserRole[],
  module: moduleByUseCase[id],
  useCases: [id],
  routes: routes as string[],
  screens: screens as string[],
  description,
  steps: steps as string[],
  keywords: keywords as string[],
}));

export const frontendManualDataset: ManualKnowledgeEntry[] = [
  ...useCaseEntries,
  {
    id: 'role_cliente',
    title: 'Que puede hacer un cliente',
    entryType: 'role',
    roles: ['cliente'],
    module: 'Marketplace de platos',
    useCases: ['CU-08', 'CU-09', 'CU-24', 'CU-25', 'CU-26', 'CU-27', 'CU-29', 'CU-30', 'CU-35'],
    routes: ['/client/explore', '/client/cart', '/client/checkout', '/client/orders'],
    screens: ['Explorar platos', 'Carrito', 'Checkout', 'Mis pedidos'],
    description: 'Un cliente explora platos, compra, paga, sigue pedidos, guarda favoritos y revisa su perfil.',
    steps: ['Explora platos.', 'Agrega al carrito.', 'Confirma checkout y pago.', 'Sigue el pedido desde Mis pedidos.'],
    keywords: ['cliente', 'comprar', 'pedir comida', 'delivery'],
  },
  {
    id: 'role_cocinero',
    title: 'Que puede hacer un cocinero',
    entryType: 'role',
    roles: ['cocinero'],
    module: 'Gestion del cocinero',
    useCases: ['CU-12', 'CU-13', 'CU-14', 'CU-15', 'CU-16', 'CU-17', 'CU-18', 'CU-19', 'CU-20', 'CU-21', 'CU-22', 'CU-23', 'CU-28'],
    routes: ['/chef/dashboard', '/chef/dishes', '/chef/menu', '/chef/inventory', '/chef/orders', '/chef/ai/assistant'],
    screens: ['Resumen general', 'Mis platos', 'Menu del dia', 'Inventario', 'Pedidos recibidos'],
    description: 'Un cocinero gestiona perfil, disponibilidad, platos, menu, inventario, pedidos, ingresos y funciones IA.',
    steps: ['Revisa el dashboard.', 'Publica platos y menu.', 'Atiende pedidos.', 'Usa IA para cocina, precios o publicaciones.'],
    keywords: ['cocinero', 'vender comida', 'publicar', 'asistente ia'],
  },
  {
    id: 'role_admin',
    title: 'Que puede hacer un administrador',
    entryType: 'role',
    roles: ['admin'],
    module: 'Confianza, administracion, seguridad y notificaciones',
    useCases: ['CU-36', 'CU-37', 'CU-38', 'CU-31', 'CU-33', 'CU-34'],
    routes: ['/admin/dashboard', '/admin/users', '/admin/chefs', '/admin/publications', '/admin/fraud'],
    screens: ['Admin dashboard', 'Usuarios', 'Cocineros', 'Publicaciones'],
    description: 'Un administrador revisa usuarios, cocineros, publicaciones, repartidores, pedidos delivery y alertas de riesgo.',
    steps: ['Entra al panel admin.', 'Elige el area en el menu lateral.', 'Revisa registros.', 'Aplica acciones disponibles.'],
    keywords: ['admin', 'administrador', 'publicaciones falsas', 'fraude'],
  },
  {
    id: 'role_repartidor',
    title: 'Que puede hacer un repartidor',
    entryType: 'role',
    roles: ['repartidor'],
    module: 'Delivery y logistica',
    useCases: ['CU-31', 'CU-33', 'CU-34'],
    routes: ['/delivery/assigned', '/delivery/active', '/delivery/routes', '/delivery/incidents'],
    screens: ['Entregas asignadas', 'Entregas activas', 'Ruta actual', 'Incidencias'],
    description: 'Un repartidor revisa entregas asignadas, entregas activas, ruta actual e incidencias.',
    steps: ['Entra a Entregas asignadas.', 'Revisa entregas activas.', 'Consulta Ruta actual.', 'Reporta incidencias.'],
    keywords: ['repartidor', 'delivery', 'ruta', 'entregas'],
  },
  {
    id: 'faq_delivery_order',
    title: 'Como pedir delivery',
    entryType: 'faq',
    roles: ['cliente', 'visitante'],
    module: 'Pedidos, checkout y pagos',
    useCases: ['CU-08', 'CU-09', 'CU-24', 'CU-25', 'CU-26', 'CU-31'],
    routes: ['/client/explore', '/client/dishes/:id', '/client/cart', '/client/checkout'],
    screens: ['Explorar platos', 'Detalle de plato', 'Carrito', 'Checkout'],
    description: 'Para pedir delivery explora un plato, agregalo al carrito, confirma checkout y elige delivery si esta disponible.',
    steps: ['Explora platos.', 'Abre el detalle.', 'Agrega al carrito.', 'En checkout elige delivery.', 'Completa el pago y sigue el pedido.'],
    keywords: ['como pido delivery', 'pedir delivery', 'entrega a domicilio'],
  },
  {
    id: 'faq_publish_plate',
    title: 'Como publicar un plato',
    entryType: 'faq',
    roles: ['cocinero'],
    module: 'Gestion del cocinero',
    useCases: ['CU-15', 'CU-23'],
    routes: ['/chef/dishes', '/chef/dishes/create', '/chef/ai/publication/use'],
    screens: ['Mis platos', 'Crear plato', 'Publicacion de platos con IA'],
    description: 'El cocinero publica platos desde Mis platos y puede usar CU-23 para mejorar textos con IA.',
    steps: ['Entra a Mis platos.', 'Crea o edita un plato.', 'Completa datos del plato.', 'Usa Publicacion de platos con IA si quieres mejorar el texto.', 'Guarda la publicacion.'],
    keywords: ['publicar plato', 'crear plato', 'vender comida'],
  },
  {
    id: 'faq_out_of_domain',
    title: 'Pregunta fuera de HomeChef',
    entryType: 'faq',
    roles: ['visitante', 'cliente', 'cocinero', 'admin', 'repartidor', 'usuario'],
    module: 'Manual contextual',
    useCases: [],
    routes: [],
    screens: [],
    description: 'El asistente solo responde preguntas sobre HomeChef.',
    steps: ['Reformula tu pregunta sobre una pantalla, rol o modulo de HomeChef.'],
    keywords: ['fisica cuantica', 'politica', 'medicina', 'criptomonedas'],
  },
];

export function getScreenForRoute(pathname: string): string {
  const hit = frontendManualDataset.find((entry) => entry.routes.some((route) => routeMatches(route, pathname)));
  return hit?.screens?.[0] || 'HomeChef';
}

export function routeMatches(pattern: string, route: string): boolean {
  if (!pattern || !route) return false;
  if (pattern === route) return true;
  const regex = new RegExp(`^${pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/:id/g, '[^/]+')}$`);
  return regex.test(route);
}
