export const ALERGENOS = [
  'GLUTEN', 'LACTEOS', 'HUEVO', 'MANI', 'FRUTOS_SECOS', 'SOYA', 'PESCADO', 'MARISCOS',
  'CRUSTACEOS', 'MOLUSCOS', 'SESAMO', 'MOSTAZA', 'APIO', 'SULFITOS', 'MAIZ', 'AJO', 'CEBOLLA', 'PICANTE',
]

export const INGREDIENTES = [
  'CARNE_RES', 'POLLO', 'CERDO', 'CHARQUE', 'CHORIZO', 'PESCADO', 'CAMARON', 'MARISCOS',
  'HUEVO', 'QUESO', 'LECHE', 'CREMA', 'ARROZ', 'FIDEO', 'PAN', 'HARINA', 'QUINUA', 'PAPA',
  'YUCA', 'CAMOTE', 'PLATANO', 'CHOCLO', 'MAIZ', 'TOMATE', 'CEBOLLA', 'ZANAHORIA', 'LECHUGA',
  'ARVEJA', 'VAINITA', 'BROCOLI', 'PIMENTON', 'LOCOTO', 'AJI', 'MANI', 'GARBANZO', 'LENTEJA',
  'FRIJOL', 'AJO', 'PEREJIL', 'CILANTRO', 'OREGANO', 'COMINO', 'PIMIENTA', 'ACEITE', 'SAL', 'AZUCAR', 'LIMON',
]

export const ETIQUETAS = [
  'CASERO', 'TRADICIONAL', 'ARTESANAL', 'POPULAR', 'RECOMENDADO', 'DESTACADO', 'NUEVO',
  'ECONOMICO', 'PROMOCION', 'PREMIUM', 'RAPIDO', 'FRESCO', 'RECIEN_HECHO', 'PARA_COMPARTIR',
  'PORCION_GRANDE', 'DESAYUNO', 'ALMUERZO', 'CENA', 'MERIENDA', 'PICANTE', 'NO_PICANTE',
  'DULCE', 'SALADO', 'AGRIDULCE', 'VEGETARIANO', 'VEGANO', 'SIN_GLUTEN', 'SIN_LACTEOS',
  'ALTO_EN_PROTEINA', 'BAJO_EN_GRASA', 'SOPA', 'PLATO_FUERTE', 'ENTRADA', 'POSTRE', 'BEBIDA',
  'SNACK', 'BOLIVIANO', 'COCHABAMBINO', 'PACENO', 'CRUCENO', 'TARIJENO',
]
